pipeline {
    agent any
    environment {
        BACKEND_IMAGE  = "moin9592/mern-backend"
        FRONTEND_IMAGE = "moin9592/mern-frontend"
        TAG = "${BUILD_NUMBER}"
        // Jenkins credentials IDs
        DOCKER_CREDS = "dockerhub-creds"
        KUBE_CONFIG  = "kubeconfig-file"
        // GitHub Repo
        GIT_URL = "https://github.com/moinbash/Three-tier-project.git"
    }
    stages {
        stage('Checkout Code from GitHub') {
            steps {
                git branch: "main", url: "${GIT_URL}"
            }
        }
        stage('Build Docker Images') {
            steps {
                dir('mern/backend') {
                    sh "docker build -t ${BACKEND_IMAGE}:${TAG} ."
                }
                dir('mern/frontend') {
                    sh "docker build -t ${FRONTEND_IMAGE}:${TAG} ."
                }
            }
        }
        stage('Push Images to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: DOCKER_CREDS,
                    usernameVariable: "DOCKER_USER",
                    passwordVariable: "DOCKER_PASS"
                )]) {
                    sh '''
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    docker push ${BACKEND_IMAGE}:${TAG}
                    docker push ${FRONTEND_IMAGE}:${TAG}
                    docker logout
                    '''
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: KUBE_CONFIG, variable: "KUBECONFIG")]) {
                    sh '''
                    echo ===== Checking kubeconfig =====
                    export KUBECONFIG=$KUBECONFIG
                    kubectl config current-context
                    kubectl get nodes
                    sed -i "s|${BACKEND_IMAGE}:.*|${BACKEND_IMAGE}:${TAG}|" k8s.yaml
                    sed -i "s|${FRONTEND_IMAGE}:.*|${FRONTEND_IMAGE}:${TAG}|" k8s.yaml
                    kubectl apply -f k8s.yaml
                    kubectl rollout restart deployment mongodb-deployment
                    kubectl rollout restart deployment backend-deployment
                    kubectl rollout restart deployment frontend-deployment
                    '''
                }
            }
        }
    }
}
